app/urls.py
from django.urls import path, include
from . import views

app_name = 'app'

urlpatterns = [
    path(r'', views.index, name='index'),
    path('docs/api/', views.docs_api, name='docs_api'),
    path('docs/sphinx/', include('docs.urls')),
    path('docs/project', views.docs_project, name='docs_project'),

]

load/urls.py
from django.conf.urls import include
from django.urls import path
from rest_framework import routers

from load.api.viewsets import LoadViewSet
from . import views

app_name = 'load'

router = routers.DefaultRouter()
router.register(r'loads', LoadViewSet, base_name='api')

urlpatterns = [
    path('api/', include(router.urls)),
    path('loads/', views.list_loads, name='loads'),
    path('create/', views.LoadCreateView.as_view(), name='create-load'),
    path('<int:pk>/update/', views.LoadUpdateView.as_view(), name='update-load'),
    path('<int:pk>/accept/', views.accept_load, name='accept-load'),
    path('<int:pk>/reject/', views.reject_load, name='reject-load'),
    path('<int:pk>/drop/', views.drop_load, name='drop-load')
]

loadsmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('load.urls', namespace='load')),
]

load/models.py
from django.db import models

from users.models import Shipper, Carrier


class LoadManager(models.Manager):
    """
    A manager for the operations on the load objects.
    """

    def get_carrier_available_loads(self, request):
        """
        Get the list of all available loads.

        The loads that the shipper dropped will not be shown as available.

        :param django.http.HttpRequest request: Received request.
        :return: List of available loads for the Carrier
        :rtype: django.db.models.QuerySet
        """

        dropped_loads = self.get_carrier_rejected_loads(request)

        return self.filter(
            carrier=None).exclude(id__in=dropped_loads)

    def get_carrier_accepted_loads(self, request):
        """
        Get the list of loads that the carrier accepted.

        :param django.http.HttpRequest request: Received request.
        :return: List of accepted loads by the Carrier
        :rtype: django.db.models.QuerySet
        """

        carrier = Carrier.objects.get_carrier(request)

        return self.filter(carrier=carrier)

    def get_carrier_rejected_loads(self, request):
        """
        Get the list of loads that the carrier rejected.

        :param django.http.HttpRequest request: Received request.
        :return: List of rejected loads by the Carrier
        :rtype: django.db.models.QuerySet
        """

        carrier = Carrier.objects.get_carrier(request)
        return carrier.dropped_by.all()

    def get_shipper_available_loads(self, request):
        """
        Get the list of the shipper loads that are still available.

        :param django.http.HttpRequest request: Received request.
        :return: List of the Shipper available loads.
        :rtype: django.db.models.QuerySet
        """

        shipper = Shipper.objects.get_shipper(request)

        return self.filter(carrier=None, shipper=shipper)

    def get_shipper_accepted_loads(self, request):
        """
        Get the list of the shipper loads that were accepted.

        :param django.http.HttpRequest request: Received request.
        return: List of the Shipper accepted loads.
        :rtype: django.db.models.QuerySet
        """

        shipper = Shipper.objects.get_shipper(request)

        return self.exclude(carrier=None).filter(shipper=shipper)


class Load(models.Model):
    """Model for the loads.

    Stores the loads information in the DB fields: shipper, carrier, pickup_date, ref number, origin_city,
    destination_city, shipper_price, carrier_price, dropped_by.
    """

    shipper = models.ForeignKey(
        Shipper, related_name='shipper', on_delete=models.PROTECT)
    carrier = models.ForeignKey(
        Carrier, related_name='carrier', on_delete=models.PROTECT, null=True, blank=True)
    pickup_date = models.DateField()
    ref = models.CharField(max_length=200)
    origin_city = models.CharField(max_length=200)
    destination_city = models.CharField(max_length=200)
    shipper_price = models.FloatField()
    carrier_price = models.FloatField()
    dropped_by = models.ManyToManyField(Carrier, related_name="dropped_by")

    objects = LoadManager()

    def __str__(self):
        return self.ref

load/forms.py
from bootstrap_modal_forms.forms import BSModalForm
from django import forms

from .models import Load


class DateInput(forms.DateInput):
    """
    Form used for pickup date input.
    """

    input_type = 'date'


class LoadForm(BSModalForm):
    """
    Popup form used for load creation.
    """

    class Meta:
        model = Load
        fields = ('pickup_date', 'ref', 'origin_city',
                  'destination_city', 'shipper_price',)
        widgets = {
            'pickup_date': DateInput(),
        }


class LoadEditRateForm(BSModalForm):
    """
    Popup form used for load rate edition.

    The shipper can edit the load price suggested by the data science model.
    """

    class Meta:
        model = Load
        fields = ('shipper_price',)

load/views.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from users.models import Carrier, Shipper
from . import utils
from .decorators import shipper_required, carrier_required, login_required
from .forms import LoadForm, LoadEditRateForm
from .models import Load


@method_decorator(shipper_required, name='dispatch')
class LoadCreateView(BSModalCreateView):
    """
    View that handles the creation of a load.

    Only a Shipper can create a load.
    """

    template_name = 'load/new_load.html'
    form_class = LoadForm
    success_message = 'Success: Load was created.'
    success_url = reverse_lazy('load:loads')

    def form_valid(self, form):
        """
        Overrides form_valid method to automatically fill out the fields carrier, carrier_price, and shipper.
        """

        load = form.save(commit=False)
        load.carrier = None
        load.carrier_price = utils.calculate_carrier_price(load.shipper_price)
        if self.request.user.is_authenticated:
            shipper = Shipper.objects.get_shipper(self.request)
            load.shipper = shipper
        load.save()

        return super(LoadCreateView, self).form_valid(form)


@method_decorator(shipper_required, name='dispatch')
class LoadUpdateView(BSModalUpdateView):
    """
    View for load rate update.

    Only Shippers are allowed to change the load rate and they can only update their on loads.
    """

    model = Load
    template_name = 'load/edit_rate.html'
    form_class = LoadEditRateForm
    success_message = 'Success: Rate was updated.'
    success_url = reverse_lazy('load:loads')

    def form_valid(self, form):
        """
        Overrides form_valid method to automatically fill out the fields carrier, carrier_price, and shipper.
        """

        load = form.save(commit=False)
        load.carrier = None
        if self.request.user.is_authenticated:
            shipper = Shipper.objects.get_shipper(self.request)
            load.shipper = shipper
            load.carrier_price = utils.calculate_carrier_price(load.shipper_price)
        load.save()
        return super(LoadUpdateView, self).form_valid(form)


@login_required
def list_loads(request):
    """View that list the loads.

    The loads lists are different for Shippers and Carriers. These lists are available for logged users only.

    :param django.http.HttpRequest request: Received request.
    :return: The page with the list of loads for the Shipper or for the Carrier, depending on the User type.
    :rtype: django.http.HttpResponse
    """

    if request.user.is_shipper:
        return list_shipper_loads(request)
    return list_carrier_loads(request)


@shipper_required
def list_shipper_loads(request):
    """
    Lists the available and accepted loads of the Shipper.

    :param django.http.HttpRequest request: Received request.
    :return: The page with the list of loads for the Shipper.
    :rtype: django.http.HttpResponse
    """

    available_loads = Load.objects.get_shipper_available_loads(request)
    accepted_loads = Load.objects.get_shipper_accepted_loads(request)
    return render(request, 'load/shipper_load_list.html',
                  {'available_loads': available_loads, 'accepted_loads': accepted_loads})


@carrier_required
def list_carrier_loads(request):
    """
    Lists the all the available loads (from all Shippers) and the accepted loads of the Carrier.

    :param django.http.HttpRequest request: Received request.
    :return: The page with the list of loads for the Carrier.
    :rtype: django.http.HttpResponse
    """

    available_loads = Load.objects.get_carrier_available_loads(request)
    accepted_loads = Load.objects.get_carrier_accepted_loads(request)
    return render(request, 'load/carrier_load_list.html',
                  {'available_loads': available_loads, 'accepted_loads': accepted_loads})


@carrier_required
def accept_load(request, pk):
    """
    Accepts an available load.

    Only Carriers can accept an available load. When the load is accepted the Carrier that accepted it
    is added to the load field "carrier".

    :param django.http.HttpRequest request: Received request.
    :param pk: Load primary key
    :return: Carrier loads list page
    :rtype: django.http.HttpResponseRedirect
    """

    load = get_object_or_404(Load, pk=pk, carrier=None)
    carrier = Carrier.objects.get_carrier(request)
    load.carrier = carrier
    load.save()
    return redirect('load:loads')


@carrier_required
def reject_load(request, pk):
    """
    Rejects an available load.

    Only Carriers can reject an available load. When the load is rejected the Carrier who rejected it
    is added to the load field "dropped_by". The load remains available, except for the Carrier who rejected it.

    :param django.http.HttpRequest request: Received request.
    :param pk: Load primary key
    :return: Carrier loads list page
    :rtype: django.http.HttpResponseRedirect
    """

    load = get_object_or_404(Load, pk=pk, carrier=None)
    carrier = Carrier.objects.get_carrier(request)
    load.dropped_by.add(carrier)
    return redirect('load:loads')


@carrier_required
def drop_load(request, pk):
    """
    Drops an accepted load.

    Only Carriers can drop an accepted load. When the load is dropped the Carrier who dropped it
    is removed to the load field "carrier". The load becomes available again, except for the Carrier who dropped it.

    :param django.http.HttpRequest request: Received request.
    :param pk: Load primary key
    :return: Carrier loads list page
    :rtype: django.http.HttpResponseRedirect
    """

    carrier = Carrier.objects.get_carrier(request)
    load = get_object_or_404(Load, pk=pk, carrier=carrier)
    load.carrier = None
    load.save()
    load.dropped_by.add(carrier)
    return redirect('load:loads')

load/templates/load/carrier_load_list.html
{% extends 'app/base.html' %}

{% block title %}
    Loads
{% endblock title %}

{% block navbar-item %}
    <a class="nav-item nav-link" href="{% url 'app:docs_api' %}"> API Doc</a>
    <a class="nav-item nav-link" href="{% url 'app:docs_project' %}"> Project Doc</a>
{% endblock navbar-item %}

{% block content %}
    {% include "load/header.html" %}

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
    <div class="row container title-table">
        <h4> Loads </h4>
    </div>

    <table class="table table-hover table-custom">
        <thead class="thead-custom">
        <tr>
            <th class="th-title" scope="col">Pickup</th>
            <th class="th-title" scope="col">Origin</th>
            <th class="th-title" scope="col">Destination</th>
            <th class="th-title" scope="col">Shipper</th>
            <th class="th-title" scope="col">Status</th>
            <th class="th-title" scope="col">Price</th>
            <th class="th-title" scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th id="par" class="span title-row" colspan="7" scope="colgroup">
                ACCEPTED
            </th>
        </tr>
        {% for load in accepted_loads %}
            <tr>
                <td>{{ load.pickup_date }}</td>
                <td>{{ load.origin_city }}</td>
                <td>{{ load.destination_city }}</td>
                <td>{{ load.shipper.user.first_name }} {{ load.shipper.user.last_name }} </td>
                <td style="color:green">Accepted</td>
                <td>${{ load.carrier_price }}</td>
                <td><a class = "btn button-custom btn-block button-cancel" href="{% url 'load:drop-load' load.id %}">Drop</a></td>
            </tr>
        {% endfor %}

        <tr>
            <th id="par" class="span title-row" colspan="7" scope="colgroup">
                AVAILABLE LOADS
            </th>
        </tr>

        {% for load in available_loads %}
            <tr>
                <td>{{ load.pickup_date }}</td>
                <td>{{ load.origin_city }}</td>
                <td>{{ load.destination_city }}</td>
                <td>{{ load.shipper.user.first_name }} {{ load.shipper.user.last_name }}</td>
                <td> Waiting</td>
                <td> ${{ load.carrier_price }}</td>
                <td>
                    <a class="btn button-custom button-drop" href="{% url 'load:reject-load' load.id %}">Reject</a>
                    <a class="btn button-custom button-accept" href="{% url 'load:accept-load' load.id %}">Accept</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

load/templates/load/edit_rate.html
{% load widget_tweaks %}
{% block content %}

    <form method="post" action="">
        {% csrf_token %}

        <div class="modal-header">
            <h3 class="modal-title">Update Rate</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">

            <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>

            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" placeholder=field.label %}
                    <div class="{% if field.errors %} invalid{% endif %}">
                        {% for error in field.errors %}
                            <p class="help-block">{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="modal-footer">
            <button type="submit" class="submit-btn btn rate-button">Update</button>
        </div>

    </form>
{% endblock %}

load/templates/load/header.html
{% load static %}
<div>
    {% if messages %}
        {% for message in messages %}
            <div style="border-radius:0;" {% if message.tags %}
                 class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0"
                 role="alert" {% endif %}>
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
</div>

load/templates/load/new_load.html
{% load static %}
{% load widget_tweaks %}
{% block content %}
    <form method="POST" class="load-form">
        <div class="modal-header">
            <h3 class="modal-title">Create Load</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div class="modal-body">
            <div class="form-group">
                {% csrf_token %}
                <label for="{{ form.pickup_date.id_for_label }}">{{ form.pickup_date.label }}</label>
                {% render_field form.pickup_date class="form-control" placeholder="mm/dd/aaaa" %}
                <label for="{{ form.ref.id_for_label }}#">{{ form.ref.label }}</label>
                {% render_field form.ref class="form-control" placeholder="ref#" %}
                <label for="{{ form.origin_city.id_for_label }}">{{ form.origin_city.label }}</label>
                {% render_field form.origin_city class="form-control" placeholder="Type a city" %}
                <label for="{{ form.destination_city.id_for_label }}">{{ form.destination_city.label }}</label>
                {% render_field form.destination_city class="form-control" placeholder="Type a city" %}
                <label for="{{ form.shipper_price.id_for_label }}">Price</label>
                {% render_field form.shipper_price class="form-control" placeholder="Sugested price" onfocus="calc_price()" %}
                {% if form.errors %}
                    {{ form.non_field_errors }}
                {% endif %}
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="save btn rate-button">Save</button>
        </div>
    </form>
    {% block extra_scripts %}
        <script type="text/javascript" src="{% static 'js/load.js' %}"></script>
    {% endblock extra_scripts %}
{% endblock %}

load/templates/load/register_load.html
{% extends 'load/base.html' %}
{% block content %}
        <h1>New load</h1>

        <form action="/" method="POST">
            <div class = "form-group">
                <label for="date">Pick up date:</label>
                <input type = "date" class = "form-control" name="date" id = "date">

                <label for="ref">Ref:</label>
                <input type = "text" class = "form-control" name="ref" id = "ref" placeholder = "Ref">

                <label for="origin">Origin city:</label>
                <input type = "text" class = "form-control" name="origin" id = "origin" placeholder = "Origin city">

                <label for="destination">Destination city:</label>
                <input type = "text" class = "form-control" name="destination" id = "destination" placeholder = "Destination city">

                <div>
                    <button type="button" class = "btn btn-primary" onclick="calc_distance()">Calculate</button>
                </div>
                <label for="price">Price</label>
                <input type = "number" step="any" class = "form-control" name="price" id = "price">

            </div>
            <button class = "btn btn-success" type="submit">Register</button>
        </form>
{% endblock %}

load/templates/load/shipper_load_list.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}
    Loads
{% endblock title %}

{% block navbar-item %}
    <a class="nav-item nav-link" href="{% url 'app:docs_api' %}"> API Doc</a>
    <a class="nav-item nav-link" href="{% url 'app:docs_project' %}"> Project Doc</a>
{% endblock navbar-item %}


{% block content %}
    {% include "load/header.html" %}
    {% load widget_tweaks %}


    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
    <div class="row container title-table">
        <h4> Posted Loads </h4>
        <button class="btn btn-secondary add-button"><i class="fas fa-plus-circle"> </i> Add new </button>
    </div>

    <table class="table table-hover table-custom">
        <thead class="thead-custom">
        <tr>
            <th class="th-title" scope="col">Pickup</th>
            <th class="th-title" scope="col">Ref#</th>
            <th class="th-title" scope="col">Origin</th>
            <th class="th-title" scope="col">Destination</th>
            <th class="th-title" scope="col">Status</th>
            <th class="th-title" scope="col">Price</th>
            <th class="th-title" scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th id="par" class="span title-row" colspan="7" scope="colgroup">
                ACCEPTED
            </th>
        </tr>
        {% for load in accepted_loads %}
            <tr>
                <td>{{ load.pickup_date }}</td>
                <td>{{ load.ref }}</td>
                <td>{{ load.origin_city }}</td>
                <td>{{ load.destination_city }}</td>
                <td> Accepted by {{ load.carrier.mc_number }} </td>
                <td>${{ load.shipper_price }}</td>
                <td></td>
            </tr>
        {% endfor %}

        <tr>
            <th id="par" class="span title-row" colspan="7" scope="colgroup">
                AVAILABLE LOADS
            </th>
        </tr>

        {% for load in available_loads %}
            <tr>
                <td>{{ load.pickup_date }}</td>
                <td>{{ load.ref }}</td>
                <td>{{ load.origin_city }}</td>
                <td>{{ load.destination_city }}</td>
                <td> Load Available</td>
                <td> ${{ load.shipper_price }}</td>
                <td>
                    <button class="btn edit-rate button-custom button-cancel btn-block" data-id="{% url 'load:update-load' load.id %}"> Edit
                        Rate
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCwkx_ql1gv3xRQtJJdn-LtQ0M2U87jFpc&libraries=places"></script>
    <script type="text/javascript">
        $(function () {

            $(".add-button").modalForm({
                formURL: "{% url 'load:create-load' %}"
            });

            $(".edit-rate").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

        });
    </script>

{% endblock content %}