app/urls.py
from django.urls import path, include
from . import views

app_name = 'app'

urlpatterns = [
    path(r'', views.index, name='index'),
    path('docs/api/', views.docs_api, name='docs_api'),
    path('docs/sphinx/', include('docs.urls')),
    path('docs/project', views.docs_project, name='docs_project'),

]

load/urls.py
from django.conf.urls import include
from django.urls import path
from rest_framework import routers

from load.api.viewsets import LoadViewSet
from . import views

app_name = 'load'

router = routers.DefaultRouter()
router.register(r'loads', LoadViewSet, base_name='api')

urlpatterns = [
    path('api/', include(router.urls)),
    path('loads/', views.list_loads, name='loads'),
    path('create/', views.LoadCreateView.as_view(), name='create-load'),
    path('<int:pk>/update/', views.LoadUpdateView.as_view(), name='update-load'),
    path('<int:pk>/accept/', views.accept_load, name='accept-load'),
    path('<int:pk>/reject/', views.reject_load, name='reject-load'),
    path('<int:pk>/drop/', views.drop_load, name='drop-load')
]

loadsmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('load.urls', namespace='load')),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register_shipper/', views.ShipperRegistrationView.as_view(),
         name='register_shipper'),
    path('register_carrier/', views.CarrierRegistrationView.as_view(),
         name='register_carrier'),
    path('token/', obtain_auth_token),

]

users/models.py
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import ugettext as _


class EmailUserManager(BaseUserManager):
    """
    A manager for User creation that requires an email and a password.
    """

    def create_user(self, *args, **kwargs):
        """
        Creates a User.

        :param args: Variable length argument list. Not used.
        :param kwargs: Key words sent to create_user method.
        :return: Created User
        :rtype: User
        """

        email = kwargs["email"]
        email = self.normalize_email(email)
        password = kwargs["password"]
        kwargs.pop("password")

        if not email:
            raise ValueError(_('Users must have an email address'))

        user = self.model(**kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, *args, **kwargs):
        """
        Creates a User with super user privileges.

        :param args: Variable length argument list. Not used.
        :param kwargs: Key words sent to create_user method.
        :return: Created User
        :rtype: User
        """

        user = self.create_user(**kwargs)
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(PermissionsMixin, AbstractBaseUser):
    """
    Model for User.

    Stores User information in the fields: email, first_name, last_name, is_shipper, is_carrier.
    The email is set to be the username. The boolean fields is_shipper and is_carrier define
    the type of user. Uses EmailUserManager.
    """

    email = models.EmailField(
        verbose_name=_('Email address'),
        unique=True,
    )
    first_name = models.CharField(
        verbose_name=_('First name'),
        max_length=50,
        blank=False,
    )
    last_name = models.CharField(
        verbose_name=_('Last name'),
        max_length=50,
        blank=False,
    )
    is_shipper = models.BooleanField(default=False)
    is_carrier = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    objects = EmailUserManager()


class ShipperManager(models.Manager):
    """
    A manager to access shipper information.
    """

    def get_shipper(self, request):
        """Gets the Shipper by the User primary key.

        :param django.http.HttpRequest request: Received request.
        :return: The Shipper that matches the User primary key.
        :rtype: Shipper
        """

        return self.get(user=request.user.pk)


class Shipper(models.Model):
    """
    Model for the Shipper

    Stores the information about Shippers. Shipper field is a foreign key from a User. Uses ShipperManager.
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    objects = ShipperManager()


class CarrierManager(models.Manager):
    """
    A manager to access Carrier information.
    """

    def get_carrier(self, request):
        """Gets the Carrier by the User primary key.

        :param django.http.HttpRequest request: Received request.
        :return: The Carrier that matches the User primary key.
        :rtype: Carrier
        """

        return self.get(user=request.user.pk)


class Carrier(models.Model):
    """
    Stores the information about Carrie.

    Carrier fields are a foreign key from a User and the mc_number. Uses CarrierManager.
    """

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    mc_number = models.CharField(max_length=8)

    objects = CarrierManager()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator

from .models import User


class ShipperCreationForm(UserCreationForm):
    """
    Form for Shipper creation.
    """

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class CarrierCreationForm(UserCreationForm):
    """
    Form for Carrier creation.

    Validates MC number format according to FMCSA website
    """

    re_mc_number = RegexValidator(
        '^[a-zA-Z]{2}[0-9]{6}$', 'MC number must be prefixed by 2 letters and followed by 6 numbers')
    mc_number = forms.CharField(required=True, validators=[re_mc_number])

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'mc_number']

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import ShipperCreationForm, CarrierCreationForm
from .models import Shipper, Carrier


class ShipperRegistrationView(CreateView):
    """
    View that handles Shipper registration.
    """

    form_class = ShipperCreationForm
    success_url = reverse_lazy('users:login')
    template_name = "users/register.html"

    def post(self, request, *args, **kwargs):
        """
        Overrides CreateView method post to include the creation of a Shipper when a User is created.

        :param django.http.HttpRequest request: Received request.
        :param args: Variable length argument list.
        :param kwargs: Arbitrary keyword arguments.
        :return: If form is valid, redirects to login page. If form is not valid, remains in the registration.
        """

        form = ShipperRegistrationView.form_class(request.POST)

        if form.is_valid():
            user = form.save()
            user.is_shipper = True
            user.save()

            shipper = Shipper.objects.create(user=user)
            shipper.save()

            return HttpResponseRedirect(self.success_url)

        return render(request, self.template_name, {'form': form})


class CarrierRegistrationView(CreateView):
    """
    View that handles Carrier registration.
    """

    form_class = CarrierCreationForm
    success_url = reverse_lazy('users:login')
    template_name = "users/register.html"

    def post(self, request, *args, **kwargs):
        """
        Overrides CreateView method post to include the creation of a Carrier when a User is created.

        :param django.http.HttpRequest request: Received request.
        :param args: Variable length argument list.
        :param kwargs: Arbitrary keyword arguments.
        :return: If form is valid, redirects to login page. If form is not valid, remains in the registration.
        """

        form = CarrierRegistrationView.form_class(request.POST)

        if form.is_valid():
            user = form.save()
            mc_number = form.cleaned_data['mc_number']
            user.mc_number = mc_number
            user.is_carrier = True
            user.save()

            carrier = Carrier.objects.create(user=user, mc_number=mc_number)
            carrier.save()

            return HttpResponseRedirect(self.success_url)

        return render(request, self.template_name, {'form': form})

users/templates/users/login.html
{% extends "app/base.html" %}
{% load static %}

{% block title %}
    Login
{% endblock title %}

{% block navbar-item %}
    <a class="nav-item nav-link" href="{% url 'app:docs_api' %}"> API Doc</a>
    <a class="nav-item nav-link" href="{% url 'app:docs_project' %}"> Project Doc</a>
{% endblock navbar-item %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock style %}

{% block content %}
    <div class="login-form">
        <form role="form" class="form" method="POST" action="{{ request.path }}{% if next %}?next={{ next }}{% endif %}">
            <div class="avatar">
                <i class="fas fa-user-alt user-icon"></i>
            </div>
            <h2 class="text-center">Login</h2>
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Username" required="required" >
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password" required="required" >
            </div>
            {% if form.errors %}
                {{ form.non_field_errors }}
            {% endif %}

            <input type="hidden" name="next" value="{% url 'load:loads' %}" />
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>
            </div>
        </form>
        <p class="text-center small">Don't have an account? </br><a href="{% url 'users:register_shipper' %}">Sign up as shipper!</a> | <a href="{% url 'users:register_carrier' %}">Sign up as carrier!</a></p>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "app/base.html" %}

{% load widget_tweaks %}

{% block title %}
    Register
{% endblock title %}

{% block navbar-item %}
    <a class="nav-item nav-link" href="{% url 'app:docs_api' %}"> API Doc</a>
    <a class="nav-item nav-link" href="{% url 'app:docs_project' %}"> Project Doc</a>

{% endblock navbar-item %}

{% block content %}
    <form method="POST" class="load-form">
        <div class="modal-header">
            <h3 class="modal-title">Register</h3>
        </div>

        <div class="modal-body">
            <div class="form-group">
                {% csrf_token %}
                {% for field in form %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" placeholder="" %}


                    {% if field.help_text %}
                        <p>
                            <small style="color: gray"> {{ field.help_text|safe }} </small>
                        </p>
                    {% endif %}

                    {% for error in field.errors %}
                        <p style="color: red"> {{ error }} </p>
                    {% endfor %}

                {% endfor %}
            </div>
        </div>

        <div class="modal-footer">
            <button type="submit" class="save btn btn-success">Save</button>
            <input type="hidden" name="next" value="{% url 'app:index' %}" />
        </div>
    </form>

{% endblock content %}