app/urls.py
from django.urls import path, include
from . import views

app_name = 'app'

urlpatterns = [
    path(r'', views.index, name='index'),
    path('docs/api/', views.docs_api, name='docs_api'),
    path('docs/sphinx/', include('docs.urls')),
    path('docs/project', views.docs_project, name='docs_project'),

]

load/urls.py
from django.conf.urls import include
from django.urls import path
from rest_framework import routers

from load.api.viewsets import LoadViewSet
from . import views

app_name = 'load'

router = routers.DefaultRouter()
router.register(r'loads', LoadViewSet, base_name='api')

urlpatterns = [
    path('api/', include(router.urls)),
    path('loads/', views.list_loads, name='loads'),
    path('create/', views.LoadCreateView.as_view(), name='create-load'),
    path('<int:pk>/update/', views.LoadUpdateView.as_view(), name='update-load'),
    path('<int:pk>/accept/', views.accept_load, name='accept-load'),
    path('<int:pk>/reject/', views.reject_load, name='reject-load'),
    path('<int:pk>/drop/', views.drop_load, name='drop-load')
]

loadsmart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('load.urls', namespace='load')),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register_shipper/', views.ShipperRegistrationView.as_view(),
         name='register_shipper'),
    path('register_carrier/', views.CarrierRegistrationView.as_view(),
         name='register_carrier'),
    path('token/', obtain_auth_token),

]

app/templates/app/api-project.html
{% extends "app/base.html" %}

{% block title %}
    Project Doc
{% endblock title %}

{% block navbar-item %}
    <a class="nav-item nav-link" href="{% url 'load:loads' %}"> Loads </a>
{% endblock navbar-item %}

{% block content %}
<style>
html, body{
    height:100%;
}
.doc_frame {
    margin-top: 0px;
    max-width: none;
    height: 100%;
    width:100%;
    min-height:100%;
}
.container{
    max-width: none;
    margin-top: 0px;
    padding-right: 0px;
    padding-left: 0px;
    height: 90%;
}
</style>

    <iframe class="doc_frame" src="../docs/sphinx/" frameborder="0" allowfullscreen></iframe>

{% endblock content %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
            integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
            integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>

        {% block style %}
        {% endblock style %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
            {% if user.is_authenticated %}
                <a class="logo-custom" href="{% url 'load:loads' %}">LOAD<b>SMART</b></a>
            {% else %}
                <a class="logo-custom" href="{% url 'users:login' %}">LOAD<b>SMART</b></a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse container-fluid" id="navbarNavDropdown">
                <div class="navbar-nav">
                    {% block navbar-item %}

                    {% endblock navbar-item %}
                </div>


                {% if user.is_authenticated %}
                    <div>
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-user"></i>
                                    {{ user.get_username }}
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </nav>


        <div class="container container-custom">
            {% block content %}

            {% endblock content %}
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
                integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
                integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
                crossorigin="anonymous"></script>
        {% block extra_scripts %}

        {% endblock extra_scripts %}
    </body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %}

{% block title %}
Loadsmart
{% endblock title %}

{% block content %}
<h1> Main page :) </h1>
{% endblock content %}